### ISSUE TITLE
请删除代码中的分号

### ISSUE THREAD

**Issue by yunline** [jimjiang2/ch341dll_wrap_typical_app#1]
为什么要给python代码加分号？画Python添足吗？
给python加分号也就忍了，为什么有几行又漏了分号？
![image](https://user-images.githubusercontent.com/31395137/236859398-59bdb731-5c93-4b5a-a166-b652e9695af1.png)
(ch341dll_32bits_wrap\ch341dll_wrap.py)

**Comment by jimjiang2** [comment]
gvim :    
%s/;\s*$//
一句搞定。
不要纠结这种无关紧要的东西，浪费精力。

**Comment by yunline** [comment]
6
